services:
  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - "5000:5000"
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
      args:
        NEXT_PUBLIC_API_BASE_PATH: /api/proxy
    ports:
      - "3000:3000"
    environment:
      - BACKEND_API_URL=http://backend:5000/api
      - NEXT_PUBLIC_API_BASE_PATH=/api/proxy
    depends_on:
      - backend